# Generated by Django 5.1.1 on 2024-10-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("settings", models.JSONField(blank=True, null=True)),
                ("analysis_result", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
